//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace ServiceReference1
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConsulatECTCRequest", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ConsulatECTCRequest : object
    {

        private bool AplicaRetCuentasField;

        private string CodProductoField;

        private string FechaFinField;

        private string FechaInicioField;

        private string IdClienteField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AplicaRetCuentas
        {
            get
            {
                return this.AplicaRetCuentasField;
            }
            set
            {
                this.AplicaRetCuentasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProducto
        {
            get
            {
                return this.CodProductoField;
            }
            set
            {
                this.CodProductoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConsulatECTCResponse", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ConsulatECTCResponse : object
    {

        private string CodErrorField;

        private ServiceReference1.EstadoCuenta[] CortesField;

        private ServiceReference1.Cuenta[] CuentasField;

        private string MsgErrorField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodError
        {
            get
            {
                return this.CodErrorField;
            }
            set
            {
                this.CodErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.EstadoCuenta[] Cortes
        {
            get
            {
                return this.CortesField;
            }
            set
            {
                this.CortesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Cuenta[] Cuentas
        {
            get
            {
                return this.CuentasField;
            }
            set
            {
                this.CuentasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgError
        {
            get
            {
                return this.MsgErrorField;
            }
            set
            {
                this.MsgErrorField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EstadoCuenta", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class EstadoCuenta : object
    {

        private string CodProductoField;

        private string FechaCorteField;

        private string IdDocumentoField;

        private string IdentClienteField;

        private string NomProductoField;

        private string NombreClienteField;

        private string NumTarjetaField;

        private int TipoBaseField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProducto
        {
            get
            {
                return this.CodProductoField;
            }
            set
            {
                this.CodProductoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCorte
        {
            get
            {
                return this.FechaCorteField;
            }
            set
            {
                this.FechaCorteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento
        {
            get
            {
                return this.IdDocumentoField;
            }
            set
            {
                this.IdDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentCliente
        {
            get
            {
                return this.IdentClienteField;
            }
            set
            {
                this.IdentClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomProducto
        {
            get
            {
                return this.NomProductoField;
            }
            set
            {
                this.NomProductoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumTarjeta
        {
            get
            {
                return this.NumTarjetaField;
            }
            set
            {
                this.NumTarjetaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoBase
        {
            get
            {
                return this.TipoBaseField;
            }
            set
            {
                this.TipoBaseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cuenta", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class Cuenta : object
    {

        private string CodProductoField;

        private string NumTarjetaField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProducto
        {
            get
            {
                return this.CodProductoField;
            }
            set
            {
                this.CodProductoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumTarjeta
        {
            get
            {
                return this.NumTarjetaField;
            }
            set
            {
                this.NumTarjetaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ECDocTCRequest", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ECDocTCRequest : object
    {

        private string IdDocumentoField;

        private string TipoArchivoField;

        private int TipoBaseField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDocumento
        {
            get
            {
                return this.IdDocumentoField;
            }
            set
            {
                this.IdDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoArchivo
        {
            get
            {
                return this.TipoArchivoField;
            }
            set
            {
                this.TipoArchivoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoBase
        {
            get
            {
                return this.TipoBaseField;
            }
            set
            {
                this.TipoBaseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ECDocTCResponse", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class ECDocTCResponse : object
    {

        private string CodErrorField;

        private string MsgErrorField;

        private byte[] ResultField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodError
        {
            get
            {
                return this.CodErrorField;
            }
            set
            {
                this.CodErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgError
        {
            get
            {
                return this.MsgErrorField;
            }
            set
            {
                this.MsgErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.IConsultaECTCService")]
    public interface IConsultaECTCService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConsultaECTCService/ConsultaEstadosDeCuentaTC", ReplyAction = "http://tempuri.org/IConsultaECTCService/ConsultaEstadosDeCuentaTCResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ConsulatECTCResponse> ConsultaEstadosDeCuentaTCAsync(ServiceReference1.ConsulatECTCRequest solicitudEstadoCta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConsultaECTCService/ConsultaDocEstadoDeCuentaTC", ReplyAction = "http://tempuri.org/IConsultaECTCService/ConsultaDocEstadoDeCuentaTCResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ECDocTCResponse> ConsultaDocEstadoDeCuentaTCAsync(ServiceReference1.ECDocTCRequest solicitudDocEstadoCta);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IConsultaECTCServiceChannel : ServiceReference1.IConsultaECTCService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ConsultaECTCServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IConsultaECTCService>, ServiceReference1.IConsultaECTCService
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ConsultaECTCServiceClient() :
                base(ConsultaECTCServiceClient.GetDefaultBinding(), ConsultaECTCServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConsultaECTCService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConsultaECTCServiceClient(EndpointConfiguration endpointConfiguration) :
                base(ConsultaECTCServiceClient.GetBindingForEndpoint(endpointConfiguration), ConsultaECTCServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConsultaECTCServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ConsultaECTCServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConsultaECTCServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ConsultaECTCServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConsultaECTCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<ServiceReference1.ConsulatECTCResponse> ConsultaEstadosDeCuentaTCAsync(ServiceReference1.ConsulatECTCRequest solicitudEstadoCta)
        {
            return base.Channel.ConsultaEstadosDeCuentaTCAsync(solicitudEstadoCta);
        }

        public System.Threading.Tasks.Task<ServiceReference1.ECDocTCResponse> ConsultaDocEstadoDeCuentaTCAsync(ServiceReference1.ECDocTCRequest solicitudDocEstadoCta)
        {
            return base.Channel.ConsultaDocEstadoDeCuentaTCAsync(solicitudDocEstadoCta);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsultaECTCService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsultaECTCService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.60.24.23/WCFConsultaECTC_APP/ConsultaECTCService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultaECTCServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConsultaECTCService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultaECTCServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConsultaECTCService);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IConsultaECTCService,
        }
    }
}
